// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4dpExp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4dpGauss_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4dpHNormal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4dpHNormalSpike_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4dpWeibull_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4redifhm_all_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4redifhm_multi_hier_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4dpExp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4dpExp_mod, 0},
    {"_rcpp_module_boot_stan_fit4dpGauss_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4dpGauss_mod, 0},
    {"_rcpp_module_boot_stan_fit4dpHNormal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4dpHNormal_mod, 0},
    {"_rcpp_module_boot_stan_fit4dpHNormalSpike_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4dpHNormalSpike_mod, 0},
    {"_rcpp_module_boot_stan_fit4dpWeibull_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4dpWeibull_mod, 0},
    {"_rcpp_module_boot_stan_fit4redifhm_all_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4redifhm_all_mod, 0},
    {"_rcpp_module_boot_stan_fit4redifhm_multi_hier_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4redifhm_multi_hier_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_MIRES(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
